/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'prsingha' at '3/15/17 5:13 PM' with Gradle 2.13
 *
 * @author prsingha, @date 3/15/17 5:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
